"""empty message

Revision ID: 2ce3ec835c4b
Revises: d6a12cec2574
Create Date: 2026-06-25 23:15:32.247259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce3ec835c4b'
down_revision = 'd6a12cec2574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fav_character_id', sa.Integer(), nullable=True),
    sa.Column('fav_planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fav_character_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fav_planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
