"""empty message

Revision ID: 6445fef0907b
Revises: f7d1b70e40eb
Create Date: 2026-06-26 00:19:08.013856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6445fef0907b'
down_revision = 'f7d1b70e40eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('birthday')

    # ### end Alembic commands ###
