"""empty message

Revision ID: f7d1b70e40eb
Revises: 2ce3ec835c4b
Create Date: 2026-06-25 23:20:59.266203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d1b70e40eb'
down_revision = '2ce3ec835c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fav_character_id', sa.Integer(), nullable=True),
    sa.Column('fav_planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fav_character_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fav_planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fav_character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fav_planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fav_character_id'], ['user.id'], name=op.f('favorite_fav_character_id_fkey')),
    sa.ForeignKeyConstraint(['fav_planet_id'], ['planet.id'], name=op.f('favorite_fav_planet_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('favorite_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('favorite_pkey'))
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
