"""empty message

Revision ID: 192c231a0f05
Revises: 892fd56afe67
Create Date: 2026-05-09 21:23:10.910516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192c231a0f05'
down_revision = '892fd56afe67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Enum('IMAGE', 'AUDIO', 'VIDEO', name='mediatype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('IMAGE', 'AUDIO', 'VIDEO', name='mediatype'),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
