"""empty message

Revision ID: 213bfde22cb6
Revises: 39dda8b0d33d
Create Date: 2026-05-09 21:33:31.455077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213bfde22cb6'
down_revision = '39dda8b0d33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Enum('IMAGE', 'AUDIO', 'VIDEO', name='mediatype'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('IMAGE', 'AUDIO', 'VIDEO', name='mediatype'),
               type_=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
