"""empty message

Revision ID: 256ff4d1458d
Revises: bd0ec8a6e602
Create Date: 2026-05-09 21:46:31.957209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256ff4d1458d'
down_revision = 'bd0ec8a6e602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'received', 'completed', name='status_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
