"""empty message

Revision ID: 274f6fa53de0
Revises: 2ebf5472174b
Create Date: 2026-05-09 03:16:27.795821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274f6fa53de0'
down_revision = '2ebf5472174b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
