"""empty message

Revision ID: 302405aa9e77
Revises: eead64210733
Create Date: 2026-05-09 20:48:27.435190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302405aa9e77'
down_revision = 'eead64210733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='media_pkey')
    )
    # ### end Alembic commands ###
