"""empty message

Revision ID: 39dda8b0d33d
Revises: 575f3d98be4c
Create Date: 2026-05-09 21:32:36.467421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39dda8b0d33d'
down_revision = '575f3d98be4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Enum('IMAGE', 'AUDIO', 'VIDEO', name='mediatype'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('IMAGE', 'AUDIO', 'VIDEO', name='mediatype'),
               type_=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
