"""empty message

Revision ID: 59f1e5016ec9
Revises: a78c443eed50
Create Date: 2026-05-11 18:22:31.029808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f1e5016ec9'
down_revision = 'a78c443eed50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('fav_character_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('fav_planet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('fav_planet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fav_character_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
