"""empty message

Revision ID: 892fd56afe67
Revises: e668d1431bfb
Create Date: 2026-05-09 21:21:56.608291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892fd56afe67'
down_revision = 'e668d1431bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rowid', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('rowid')

    # ### end Alembic commands ###
