"""empty message

Revision ID: bd0ec8a6e602
Revises: 2eb77f310869
Create Date: 2026-05-09 21:42:26.716721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0ec8a6e602'
down_revision = '2eb77f310869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Enum('IMAGE', 'AUDIO', 'VIDEO', name='mediatype'),
               existing_nullable=False)
        batch_op.drop_constraint('media_type_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_unique_constraint('media_type_key', ['type'])
        batch_op.alter_column('type',
               existing_type=sa.Enum('IMAGE', 'AUDIO', 'VIDEO', name='mediatype'),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
