"""empty message

Revision ID: d54f9c4da2f8
Revises: f4c16e06165a
Create Date: 2026-05-11 18:16:44.353500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54f9c4da2f8'
down_revision = 'f4c16e06165a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fav_character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fav_character_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('follower')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_text', sa.String(length=1000), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('post_text')

    op.create_table('follower',
    sa.Column('user_from_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_to_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], name='follower_user_from_id_fkey'),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], name='follower_user_to_id_fkey')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
