"""empty message

Revision ID: eead64210733
Revises: ebafb0a543f9
Create Date: 2026-05-09 20:12:07.028961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eead64210733'
down_revision = 'ebafb0a543f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('AUDIO', 'VIDEO', 'TEXT', 'LINK', name='mediatype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
