"""empty message

Revision ID: f2ea06eb3ae0
Revises: 2c856919ecb1
Create Date: 2026-05-11 17:21:20.114450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ea06eb3ae0'
down_revision = '2c856919ecb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Float(), nullable=False))
        batch_op.drop_constraint('planet_email_key', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('planet_email_key', ['email'])
        batch_op.drop_column('size')

    # ### end Alembic commands ###
