"""empty message

Revision ID: 365f8af91367
Revises: 1dff8689e190
Create Date: 2026-05-09 20:54:38.832246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365f8af91367'
down_revision = '1dff8689e190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(length=500), nullable=False))
        batch_op.create_unique_constraint(None, ['url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('url')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
