"""empty message

Revision ID: 615f7f49aaad
Revises: 365f8af91367
Create Date: 2026-05-09 20:57:33.935457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615f7f49aaad'
down_revision = '365f8af91367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
