"""empty message

Revision ID: 89ae54612498
Revises: c6c811512b7e
Create Date: 2026-05-09 21:27:41.169354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ae54612498'
down_revision = 'c6c811512b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Enum('IMAGE', 'AUDIO', 'VIDEO', name='type'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('IMAGE', 'AUDIO', 'VIDEO', name='type'),
               type_=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
